var customers = [
  {
    first_name: "Lorry",
    last_name: "Copp",
    email: "lcopp0@wordpress.org",
    phone: "202-553-5284",
    address: "7 Hanover Hill",
    city: "Washington",
    state: "DC",
    zip: "20016",
  },
  {
    first_name: "Hinze",
    last_name: "Van Der Weedenburg",
    email: "hvanderweedenburg1@wp.com",
    phone: "217-790-2948",
    address: "2091 Golf Course Plaza",
    city: "Decatur",
    state: "IL",
    zip: "62525",
  },
  {
    first_name: "Kipp",
    last_name: "Spencers",
    email: "kspencers2@webeden.co.uk",
    phone: "860-905-2220",
    address: "1 Westerfield Drive",
    city: "Hartford",
    state: "CT",
    zip: "06160",
  },
  {
    first_name: "Leone",
    last_name: "Dorking",
    email: "ldorking3@mysql.com",
    phone: "559-353-6033",
    address: "2 Ruskin Road",
    city: "Visalia",
    state: "CA",
    zip: "93291",
  },
  {
    first_name: "Elisha",
    last_name: "Satchel",
    email: "esatchel4@discuz.net",
    phone: "850-756-8611",
    address: "289 Evergreen Center",
    city: "Pensacola",
    state: "FL",
    zip: "32511",
  },
];

export { customers }