var teams = [
  {
    team_name: "Ntag",
    first_name: "Harvey",
    last_name: "Alker",
    email: "halker0@photobucket.com",
    phone: "515-299-4604",
    address: "3 Magdeline Junction",
    city: "Des Moines",
    state: "IA",
    zip: "50347",
    projects: "Supervisor",
  },
  {
    team_name: "Thoughtstorm",
    first_name: "Connie",
    last_name: "Meadus",
    email: "cmeadus1@mlb.com",
    phone: "469-346-9385",
    address: "373 Vernon Terrace",
    city: "Irving",
    state: "TX",
    zip: "75062",
    projects: "Architect",
  },
  {
    team_name: "Blogspan",
    first_name: "Valli",
    last_name: "Stallybrass",
    email: "vstallybrass2@miitbeian.gov.cn",
    phone: "803-554-2723",
    address: "07914 Anzinger Alley",
    city: "Columbia",
    state: "SC",
    zip: "29208",
    projects: "Electrician",
  },
  {
    team_name: "Cogibox",
    first_name: "Aldo",
    last_name: "Whatson",
    email: "awhatson3@ibm.com",
    phone: "505-706-1569",
    address: "51791 Monica Drive",
    city: "Santa Fe",
    state: "NM",
    zip: "87505",
    projects: "Estimator",
  },
  {
    team_name: "Yozio",
    first_name: "Lacy",
    last_name: "Kearford",
    email: "lkearford4@squidoo.com",
    phone: "323-462-9042",
    address: "9 Anniversary Park",
    city: "Long Beach",
    state: "CA",
    zip: "90810",
    projects: "Construction Worker",
  },
];

export { teams }